GET http://localhost:5005/api/keys

###
GET http://localhost:5005/api/get-otp

###
POST http://localhost:5005/api/send-api
Content-Type: application/json

{
    "api": "http://localhost:3000/bayanno/home"
}


###
POST http://localhost:5005/api/save-encrypted-data
Content-Type: application/json

{
   "name": "ahshggh",
   "email": "shhjdhsmsjsdfs"
}


###
GET http://localhost:5005/api/get-user-data

